// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_DAicq4mhabdJQR8uMuAwBXiqI_OJerA',
    appId: '1:333054995616:web:5bfc6893088d6b7dddadc5',
    messagingSenderId: '333054995616',
    projectId: 'mislabs-f76b2',
    authDomain: 'mislabs-f76b2.firebaseapp.com',
    storageBucket: 'mislabs-f76b2.firebasestorage.app',
    measurementId: 'G-BKNXQ7MZ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCEV9PEp1rqc2a_c3c-hcetnuSMPajL4',
    appId: '1:333054995616:android:d09cc60b492a8b90ddadc5',
    messagingSenderId: '333054995616',
    projectId: 'mislabs-f76b2',
    storageBucket: 'mislabs-f76b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNu4buWp-jIzXbX22ssp2rjo1HbxZcveI',
    appId: '1:333054995616:ios:93a9330e316c7f4addadc5',
    messagingSenderId: '333054995616',
    projectId: 'mislabs-f76b2',
    storageBucket: 'mislabs-f76b2.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNu4buWp-jIzXbX22ssp2rjo1HbxZcveI',
    appId: '1:333054995616:ios:93a9330e316c7f4addadc5',
    messagingSenderId: '333054995616',
    projectId: 'mislabs-f76b2',
    storageBucket: 'mislabs-f76b2.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_DAicq4mhabdJQR8uMuAwBXiqI_OJerA',
    appId: '1:333054995616:web:c612476cd10a403bddadc5',
    messagingSenderId: '333054995616',
    projectId: 'mislabs-f76b2',
    authDomain: 'mislabs-f76b2.firebaseapp.com',
    storageBucket: 'mislabs-f76b2.firebasestorage.app',
    measurementId: 'G-4RG8C0VBGG',
  );
}
